### ISSUE TITLE
GeobiPy plotting script (on yeti) requires older version of pandas

### ISSUE THREAD

**Issue by ghost** [usgs/geobipy#1]
I need to update geobipy since Pandas removed their fast moving average window!

GeoBIPy works with 0.19.2

**Comment by cultpenguin** [comment]
Using Pandas version 0.23.3, the following seems to work:

Disable line 5:
#from pandas import rolling_mean as rmean

and update
       #x[:-1] = rmean(self.x, 2)
to
        x[:-1] = self.x.rolling(2).mean()

and 

#y[:-1] = rmean(self.y, 2)
y[:-1] = self.y.rolling(2).mean()

#e[:-1] = rmean(self.elevation, 2)
e[:-1] = self.elevation.rolling(2).mean()

**Comment by leonfoks** [comment]
Awesome!  Thanks for figuring this out!

**Comment by leonfoks** [comment]
Oops, i didnt actually fix this in the code, will reopen until I get this in

**Comment by leonfoks** [comment]
This is now fixed.  Thanks again!
