### ISSUE TITLE
 self.savePNG = True does not work without X

### ISSUE THREAD

**Issue by cultpenguin** [usgs/geobipy#15]
Hi 

I run geobipySerial on a remote machine, and I do not use the X-server. 
If I use 

```
self.plot = False
self.savePNG = True
```
then geobipySerial stops with an error when the png file is being created: 
"_tkinter.TclError: couldn't connect to display "localhost:12.0" 
Is it possible to use another backend with matplotlib in this case (when self.plot=False) that does not need an Xserver?

The code runs fine if I use 

```
self.plot = False
self.savePNG = False
```
Also, it would be nice if the progress of geobipySerial could be written to the console. Perhaps this is already an option?

Have a great day
- Thomas

**Comment by leonfoks** [comment]
The same fix as #16  should work for this too.
