### ISSUE TITLE
Running geobipy from Python

### ISSUE THREAD

**Issue by cultpenguin** [usgs/geobipy#17]
Hi 
Is there an example of howto run geobipy from within python, without the need to run it from the command line?
- Thomas

**Comment by leonfoks** [comment]
I don't actually!

But you should be able to do the following

```
from geobipy import singleCore
singleCore(<file to userParameter file>, <directory to write results to>)
```

singleCore is located in the uppermost __init__.py file.

**Comment by leonfoks** [comment]
@cultpenguin did this work? Can I close this?
