### ISSUE TITLE
Problem for Installing a serial version of GeoBIPy

### ISSUE THREAD

**Issue by lacorey14** [usgs/geobipy#27]
I followed your instruction in the Documentation, the error messages are:

(base) C:\geobipy-master>setup.py install
Traceback (most recent call last):
  File "C:\geobipy-master\setup.py", line 25, in <module>
    long_description=readme(),
  File "C:\geobipy-master\setup.py", line 18, in readme
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 870: illegal multibyte sequence

**Comment by leonfoks** [comment]
Thanks for the report, 

I pushed some changes to the setup file to enforce utf-8 decoding.  
Can you try again please?  Re-open this issue if it still fails!

**Comment by lacorey14** [comment]
Thanks. Probem solved!
