### ISSUE TITLE
Will docs for using the code in Windows be available?

### ISSUE THREAD

**Issue by lacorey14** [usgs/geobipy#28]
Hi there! I have installed the serial version of the code. When I followed the instruction to install the parallel version or TDEM modeller, it seems that the tutorial is not for Windows system.

**Comment by leonfoks** [comment]
The time domain forward modeller should be installable on a Windows machine, if you go to that repository, I think there are prebuilt binaries for a windows installation.

The parallelism in GeoBIPy is built for distributed memory systems using MPI. These types of machines are almost exclusively Linux based and not windows so my parallel install instructions will only be for Linux.  

I have considered having a threading enabled version of parallelism that could run on both operating systems. There might be complications storing the results in HDF5 though so I haven’t taken that step yet.
