### ISSUE TITLE
Easier way to plot subplots of inversion results

### ISSUE THREAD

**Issue by pbedros** [usgs/geobipy#4]
I'm trying to plot some single-site results from geobipy. I can create the 'full' site plot using:

    R = LR.getResults(LR.iDs[point])
    R.plot(forcePlot=True)

Is there an easy way to plot just the component pieces of this figure (say just the histogram plot and the layer-depth historgram?

**Comment by leonfoks** [comment]
I've added more routines to the Results object.
Take a look at https://github.com/usgs/geobipy/blob/master/geobipy/documentation/notebooks/Inversion%20Results%20for%20a%20single%20data%20point.ipynb

to see the function calls
