### ISSUE TITLE
plotting single-site results by fiducial, northing, easting, etc

### ISSUE THREAD

**Issue by pbedros** [usgs/geobipy#5]
when using the plotDataPoints.py script, is there a way to select the sounding to be plotted by either its fiducial value or by the northing or easting value?

**Comment by leonfoks** [comment]
- [ ] I need to add the plotting scripts to geobipy as hooks
- [ ] Update plotDataPoints to accept fiducials as well as data point indices

**Comment by leonfoks** [comment]
I've now added these scripts as examples, and have added the option to plot by fiducial in the plotDatapoints script
