### ISSUE TITLE
allowed column header names in data file

### ISSUE THREAD

**Issue by bminsley** [usgs/geobipy#8]
document somewhere allowed column header names.  There is a list printed in the .out file when you get one wrong, but can we include them someplace else?

**Comment by leonfoks** [comment]
Agreed, I will update the docs to include correct file format and samples.

**Comment by leonfoks** [comment]
Okay I've included this info in the docs.
[Time domain](https://usgs.github.io/geobipy/examples/Data/plot_time_domain_dataset.html#file-format-for-time-domain-data)
[Frequency domain](https://usgs.github.io/geobipy/examples/Data/plot_frequency_dataset.html#file-format-for-frequency-domain-data)
